source 'http://rubygems.org'

gem 'rake'
gem 'jekyll', '~> 3.8.1'
gem 'jekyll-contentblocks', '1.2.0'
gem 'jekyll_oembed', :require => 'jekyll_oembed'
gem 'pygments.rb'
gem 'kramdown'
gem 'pry-byebug'
gem 'wkhtmltopdf-binary'
